pipeline {
    agent any

    triggers {
        githubPush()
    }

    environment {
        // Define environment variables if needed
        // For example:
        // CMAKE_VERSION = '3.21.2'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the GitHub repository
                script {
                    checkout scm
                }
            }
        }

        stage('Build') {
            steps {
                // Run CMake and build your C++ project
                script {
                    sh 'cmake .'
                    sh 'make'
                    // Add additional build steps as needed
                }
            }
        }

        stage('Test') {
            steps {
                // Run tests or any other post-build steps
                script {
                    // Example: Run unit tests
                    sh 'make test'
                }
            }
        }

        // Add more stages as needed (e.g., deployment)

    }

    post {
        success {
            // Post-build actions for success
            echo 'Build successful!'
        }
        failure {
            // Post-build actions for failure
            echo 'Build failed!'
        }
    }
}
