model:

  batch: 1
  subdivisions: 1
  height: 256
  width: 256
  channels: 3

  max_batches: 100
  momentum: 0.9
  decay: 0.0005

  augmentation:
    enabled: True
    # angle: 7
    # aspect: 0.75
    flip: True
    jitter: 0.2
    saturation: 0.75
    exposure: 0.75
    hue: 0.1

  gradient_rescale:
    enabled: True
    threshold: 100.0

  gradient_clipping:
    enabled: False
    value: 100.0

  validation:
    enabled: True
    interval: 10000
    batch_size: 100
    threshold: 0.2

  save_weights_interval: 1000
  write_metrics_interval: 1000

  learning_rate:
    burn_in:
      batches: 1000
      power: 4.0

    initial_learning_rate: 0.001
    policy: smooth_stepped

    random:
      min_learning_rate: 0.00001
      update_interval: 10000

    cosine_annealing:
      min_learning_rate: 0.00001
      batches_per_cycle: 10000

    smooth_stepped:
      steps: [ 0, 10000, 20000, 30000 ]
      targets: [ 0.001, 0.0003, 0.0002, 0.0001 ]

    sigmoid:
      target_learning_rate: 0.000001
      factor: 12.0

  layers:
    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 7
      stride: 2
      pad: True
      activation: leaky

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: linear

    - type: shortcut
      activation: leaky
      from: -3

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: linear

    - type: shortcut
      activation: leaky
      from: -3

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 2
      pad: True
      activation: leaky

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: linear

    - type: shortcut
      activation: leaky
      from: -3

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: linear

    - type: shortcut
      activation: leaky
      from: -3

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 2
      pad: True
      activation: leaky

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: linear

    - type: shortcut
      activation: leaky
      from: -3

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: linear

    - type: shortcut
      activation: leaky
      from: -3

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 3
      stride: 2
      pad: True
      activation: leaky

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 3
      stride: 1
      pad: True
      activation: linear

    - type: shortcut
      activation: leaky
      from: -3

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 3
      stride: 1
      pad: True
      activation: linear

    - type: shortcut
      activation: leaky
      from: -3

    - type: avgpool

    - type: conv
      filters: 1000
      kernel: 1
      stride: 1
      pad: True
      activation: linear

    - type: softmax
      groups: 1
