model:
  batch: 1
  subdivisions: 1
  width: 416
  height: 416
  channels: 3

  momentum: 0.9
  decay: 0.0005

  max_batches: 250000

  augmentation:
    enabled: False
    flip: True
    jitter: 0.3
    saturation: 1.5
    exposure: 1.5
    hue: 0.1

  gradient_rescale:
    enabled: True
    threshold: 100.0

  gradient_clipping:
    enabled: True
    value: 100.0

  validation:
    enabled: True
    interval: 1000
    batch_size: 100
    threshold: 0.2

  save_weights_interval: 10000
  write_metrics_interval: 1000

  learning_rate:
    burn_in:
      batches: 1000
      power: 4.0

    initial_learning_rate: 0.001
    policy: inverse

    random:
      min_learning_rate: 0.00001
      update_interval: 10000

    cosine_annealing:
      min_learning_rate: 0.00001
      batches_per_cycle: 10000

    smooth_stepped:
      steps: [ 0, 10000, 20000, 30000 ]
      targets: [ 0.001, 0.0003, 0.0002, 0.0001 ]

    sigmoid:
      target_learning_rate: 0.000001
      factor: 12.0

    inverse:
      gamma: 0.0000001
      power: 12

    stepped:
      steps: [ -1, 100, 20000, 30000 ]
      scales: [ 0.1, 10, 0.1, 0.1 ]

  layers:
    - type: conv
      batch_normalize: True
      filters: 16
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 32
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: maxpool
      kernel: 2
      stride: 1

    - type: conv
      batch_normalize: True
      filters: 1024
      kernel: 3
      stride: 1
      pad: True
      activation: leaky

    - type: conv
      batch_normalize: True
      kernel: 3
      stride: 1
      pad: True
      filters: 1024
      activation: leaky

    - type: conv
      kernel: 1
      stride: 1
      pad: True
      filters: 125
      activation: linear

    - type: region
      anchors: [ 1.08, 1.19, 3.42, 4.41, 6.63, 11.38, 9.42, 5.11, 16.62, 10.52 ]
      bias_match: True
      classes: 20
      coords: 4
      num: 5
      softmax: True
      rescore: True
      object_scale: 5
      noobject_scale: 1
      class_scale: 1
      coord_scale: 1
      thresh: 0.6
