model:
  batch: 1
  subdivisions: 1
  channels: 3
  height: 416
  width: 416

  max_batches: 50000
  burn_in: 1000

  policy: steps
  learning_rate: 0.0005

  steps: [ 100, 200, 300, 20000, 30000 ]
  scales: [ 0.5, 0.5, 0.5, 0.1, 0.1 ]

  momentum: 0.9
  decay: 0.0005

  augment: False

  angle: 0
  saturation: 1.5
  exposure: 1.5
  hue: .1

  ########################################
  # EXPERIMENTAL NEW LR CONFIGURATION
  learning_rate2:
    policy: smooth_steps

    inverse:
      gamma: 0.0001
      power: 1
    
    stepped:
      steps: [ 100, 200, 300, 20000, 30000 ]
      scales: [ 0.5, 0.5, 0.5, 0.1, 0.1 ]

    smooth_stepped:
      initial_learning_rate: 0.01
      steps: [ 100, 200, 300, 20000, 30000 ]
      targets: [ 0.005, 0.00125, 0.0005, 0.0001, 0.00001 ]

  ########################################

  layers:
    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 16
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 32
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 64
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 128
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 512
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 1

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 1024
      kernel: 3
      pad: True
      stride: 1

    ###########

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 1
      pad: True
      stride: 1

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 512
      kernel: 3
      pad: True
      stride: 1

    - type: conv
      activation: linear
      dilation: 1
      filters: 255
      kernel: 1
      pad: True
      stride: 1

    - type: yolo
      mask: [ 3,4,5 ]
      anchors: [ 10,14,23,27,37,58,81,82,135,169,344,319 ]
      num: 6
      jitter: 0.3
      ignore_thresh: 0.7
      truth_thresh: 1.0
      random: True

    - type: route
      layers: [ -4 ]

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 128
      kernel: 1
      pad: True
      stride: 1

    - type: upsample
      stride: 2

    - type: route
      layers: [ -1, 8 ]

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 3
      pad: True
      stride: 1

    - type: conv
      activation: linear
      dilation: 1
      filters: 255
      kernel: 1
      pad: True
      stride: 1

    - type: yolo
      mask: [ 0,1,2 ]
      anchors: [ 10,14,23,27,37,58,81,82,135,169,344,319 ]
      num: 6
      jitter: .3
      ignore_thresh: .7
      truth_thresh: 1.0
      random: True
