model:
  batch: 1
  subdivisions: 1
  channels: 3
  height: 416
  width: 416

  max_batches: 2500000

  momentum: 0.9
  decay: 0.0005

  save_weights_interval: 10000
  write_metrics_interval: 1000

  augmentation:
    enabled: True
    flip: True
    jitter: 0.2
    saturation: 1.2
    exposure: 1.2
    hue: 0.1

  gradient_rescale:
    enabled: True
    threshold: 100.0

  gradient_clipping:
    enabled: True
    value: 100.0

  validation:
    enabled: True
    interval: 1000
    batch_size: 100
    threshold: 0.2

  learning_rate:
    burn_in:
      batches: 1000
      power: 4.0

    initial_learning_rate: 0.0005
    policy: constant

    random:
      min_learning_rate: 0.00001
      update_interval: 10000

    cosine_annealing:
      min_learning_rate: 0.00001
      batches_per_cycle: 10000

    smooth_stepped:
      steps: [ 0, 10000, 20000, 30000 ]
      targets: [ 0.001, 0.0003, 0.0002, 0.0001 ]

    sigmoid:
      target_learning_rate: 0.000001
      factor: 12.0

    inverse:
      gamma: 0.0000001
      power: 12

    stepped:
      steps: [ 400000, 450000 ]
      scales: [ 0.1, 0.1 ]

  layers:
    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 16
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 32
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 64
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 128
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 512
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 1

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 1024
      kernel: 3
      pad: True
      stride: 1

    ###########

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 1
      pad: True
      stride: 1

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 512
      kernel: 3
      pad: True
      stride: 1

    - type: conv
      activation: linear
      dilation: 1
      filters: 255
      kernel: 1
      pad: True
      stride: 1

    - type: yolo
      mask: [ 3, 4, 5 ]
      anchors: [ 10,14, 23,27, 37,58, 81,82, 135,169, 344,319 ]
      num: 6
      ignore_thresh: 0.7
      truth_thresh: 1.0
      coord_scale: 1.0
      object_scale: 5.0
      noobject_scale: 1.0
      class_scale: 1.0

    - type: route
      layers: [ -4 ]

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 128
      kernel: 1
      pad: True
      stride: 1

    - type: upsample
      stride: 2

    - type: route
      layers: [ -1, 8 ]

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 3
      pad: True
      stride: 1

    - type: conv
      activation: linear
      dilation: 1
      filters: 255
      kernel: 1
      pad: True
      stride: 1

    - type: yolo
      mask: [ 0, 1, 2 ]
      anchors: [ 10,14, 23,27, 37,58, 81,82, 135,169, 344, 319 ]
      num: 6
      ignore_thresh: 0.7
      truth_thresh: 1.0
      coord_scale: 1.0
      object_scale: 5.0
      noobject_scale: 1.0
      class_scale: 1.0
