model:
  batch: 1
  channels: 3
  height: 448
  width: 448

  max_batches: 1000000
  momentum: 0.9
  decay: 0.0005

  augmentation:
    enabled: True
    flip: True
    jitter: 0.2
    hue: 0.1
    saturation: 0.75
    exposure: 0.75

  gradient_rescale:
    enabled: True
    threshold: 100.0

  gradient_clipping:
    enabled: False
    value: 100.0

  validation:
    enabled: True
    interval: 1000
    batch_size: 100
    threshold: 0.2

  save_weights_interval: 10000
  write_metrics_interval: 1000

  learning_rate:
    burn_in:
      batches: 1000
      power: 4.0

    initial_learning_rate: 0.001
    policy: inverse

    random:
      min_learning_rate: 0.00001
      update_interval: 10000

    cosine_annealing:
      min_learning_rate: 0.00001
      batches_per_cycle: 10000

    smooth_stepped:
      steps: [ 0, 10000, 20000, 30000 ]
      targets: [ 0.001, 0.0003, 0.0002, 0.0001 ]

    sigmoid:
      target_learning_rate: 0.000001
      factor: 12.0

    inverse:
      gamma: 0.0000001
      power: 12

    stepped:
      steps: [ -1, 100, 20000, 30000 ]
      scales: [ 0.1, 10, 0.1, 0.1 ]

  layers:
    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 16
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 32
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 64
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 128
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 512
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 1024
      kernel: 3
      pad: True
      stride: 1

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 3
      pad: True
      stride: 1

    - type: connected
      activation: linear
      output: 1470

    - type: detection
      class_scale: 1
      coord_scale: 5
      coords: 4
      jitter: 0.2
      noobject_scale: 0.5
      num: 2
      object_scale: 1
      rescore: True
      side: 7
      softmax: False
      sqrt: True
