model:
  batch: 1
  channels: 3
  height: 448
  width: 448

  saturation: .75
  exposure: .75
  hue: .1

  augment: False

  gamma: 0.0001
  power: 1

  learning_rate: 0.001
  max_batches: 100
  momentum: 0.9
  decay: 0.0005

  policy: steps
  steps: [ -1, 100, 20000, 30000 ]
  scales: [ 0.1, 10, 0.1, 0.1 ]

  layers:
    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 16
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 32
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 64
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 128
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 512
      kernel: 3
      pad: True
      stride: 1

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 1024
      kernel: 3
      pad: True
      stride: 1

    - type: conv
      activation: leaky
      batch_normalize: True
      dilation: 1
      filters: 256
      kernel: 3
      pad: True
      stride: 1

    - type: connected
      activation: linear
      output: 1470

    - type: detection
      class_scale: 1
      coord_scale: 5
      coords: 4
      jitter: 0.2
      noobject_scale: 0.5
      num: 2
      object_scale: 1
      rescore: True
      side: 7
      softmax: False
      sqrt: True
