model:
  batch: 1
  subdivisions: 1
  width: 640
  height: 640
  channels: 3

  max_batches: 2000200

  momentum: 0.9
  decay: 0.0005

  augmentation:
    enabled: True
    flip: True
    jitter: 0.2
    saturation: 1.5
    exposure: 1.5
    hue: 0.1

  gradient_rescale:
    enabled: True
    threshold: 100.0

  gradient_clipping:
    enabled: False
    value: 100.0

  validation:
    enabled: True
    interval: 10000
    batch_size: 100
    threshold: 0.2

  save_weights_interval: 10000
  write_metrics_interval: 1000

  learning_rate:
    burn_in:
      batches: 0
      power: 4.0

    initial_learning_rate: 0.00261
    policy: stepped

    stepped:
      steps: [ 1600000, 1800000 ]
      scales: [ .1, .1 ]

  layers:
    - type: conv
      batch_normalize: True
      filters: 32
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 2
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 2
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -2 ]

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -3, -5, -7 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -3 ]

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 2
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -4 ]

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -2 ]

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -3, -5, -7 ]

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -3 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 2
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -4 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -2 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -3, -5, -7 ]

    - type: conv
      batch_normalize: True
      filters: 1024
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -3 ]

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 3
      stride: 2
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -4 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -2 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -3, -5, -7 ]

    - type: conv
      batch_normalize: True
      filters: 1024
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -2 ]

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      kernel: 3
      stride: 1
      pad: True
      filters: 512
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: maxpool
      stride: 1
      kernel: 5

    - type: route
      layers: [ -2 ]

    - type: maxpool
      stride: 1
      kernel: 9

    - type: route
      layers: [ -4 ]

    - type: maxpool
      stride: 1
      kernel: 13

    - type: route
      layers: [ -6, -5, -3, -1 ]

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      kernel: 3
      stride: 1
      pad: True
      filters: 512
      activation: swish

    - type: route
      layers: [ -1, -13 ]

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: upsample
      stride: 2

    - type: route
      layers: [ 42 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -3 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -2 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -2, -3, -4, -5, -7 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: upsample
      stride: 2

    - type: route
      layers: [ 27 ]

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -3 ]

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -2 ]

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 64
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers:
        - -1
        - -2
        - -3
        - -4
        - -5
        - -7
    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -3 ]

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 2
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -4, 86 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -2 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 128
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -2, -3, -4, -5, -7 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: maxpool
      kernel: 2
      stride: 2

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -3 ]

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 2
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -4, 72 ]

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -2 ]

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: conv
      batch_normalize: True
      filters: 256
      kernel: 3
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ -1, -2, -3, -4, -5, -7 ]

    - type: conv
      batch_normalize: True
      filters: 512
      kernel: 1
      stride: 1
      pad: True
      activation: swish

    - type: route
      layers: [ 100 ]

    - type: conv
      batch_normalize: True
      kernel: 3
      stride: 1
      pad: True
      filters: 256
      activation: swish

    - type: conv
      kernel: 1
      stride: 1
      pad: True
      filters: 255
      activation: logistic

    - type: yolo
      mask: [ 0, 1, 2 ]
      anchors: [ 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401 ]
      classes: 80
      num: 9
      jitter: 0.1
      ignore_thresh: 0.7
      truth_thresh: 1

    - type: route
      layers: [ 115 ]

    - type: conv
      batch_normalize: True
      kernel: 3
      stride: 1
      pad: True
      filters: 512
      activation: swish

    - type: conv
      kernel: 1
      stride: 1
      pad: True
      filters: 255
      activation: logistic

    - type: yolo
      mask: [ 3, 4, 5 ]
      anchors: [ 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401 ]
      classes: 80
      num: 9
      ignore_thresh: 0.7
      truth_thresh: 1

    - type: route
      layers: [ 130 ]

    - type: conv
      batch_normalize: True
      kernel: 3
      stride: 1
      pad: True
      filters: 1024
      activation: swish

    - type: conv
      kernel: 1
      stride: 1
      pad: True
      filters: 255
      activation: logistic

    - type: yolo
      mask: [ 6, 7, 8 ]
      anchors: [ 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401 ]
      classes: 80
      num: 9
      ignore_thresh: 0.7
      truth_thresh: 1
